on:
  push:
  workflow_dispatch:

jobs:
  ci-dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

#      - name: Linting
#        run: pnpm lint

#      - name: Auditing
#        run: pnpm audit

      - name: Build static site
        env:
          VITE_EMAILJS_PUBLIC_KEY: ${{ secrets.VITE_EMAILJS_PUBLIC_KEY }}
          VITE_EMAILJS_SERVICE_ID: ${{ secrets.VITE_EMAILJS_SERVICE_ID }}
          VITE_EMAILJS_TEMPLATE_ID:  ${{ secrets.VITE_EMAILJS_TEMPLATE_ID_DEV }}
        run: pnpm build

      - name: Deploy to Netlify
        uses: South-Paw/action-netlify-deploy@v1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID_DEV }}
          build-dir: "./dist"

  ci-prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/stable'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: stable

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

#      - name: Linting
#        run: pnpm lint

#      - name: Auditing
#        run: pnpm audit

      - name: Build static site
        env:
          VITE_EMAILJS_PUBLIC_KEY: ${{ secrets.VITE_EMAILJS_PUBLIC_KEY }}
          VITE_EMAILJS_SERVICE_ID: ${{ secrets.VITE_EMAILJS_SERVICE_ID }}
          VITE_EMAILJS_TEMPLATE_ID:  ${{ secrets.VITE_EMAILJS_TEMPLATE_ID_PROD }}
        run: pnpm build

      - name: Deploy to Netlify
        uses: South-Paw/action-netlify-deploy@v1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID_PROD }}
          build-dir: "./dist"
